version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:2.6.8
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test

workflows:
  build_and_test_deploy:
    jobs:
      - build_and_test
